package api                                                                                                                                                                                                                                    
                  
import (                                                                                                                                                                                                                                       
    "context"   
    "encoding/json"                                                                                                                                                                                                                            
    "fmt"                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                               
    "github.com/spf13/cobra"                                                                                                                                                                                                                   
    "codeup.aliyun.com/5edbc121d1d1abe63b55f1c7/soke/soke-cli/internal/client"                                                                                                                                                                                           
    "codeup.aliyun.com/5edbc121d1d1abe63b55f1c7/soke/soke-cli/internal/core"                                                                                                                                                                                             
)                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                 
func NewAPICmd() *cobra.Command {                                                                                                                                                                                                              
    var (                                                                                                                                                                                                                                      
        params string                                                                                                                                                                                                                          
        data   string                                                                                                                                                                                                                          
        asType string                                                                                                                                                                                                                          
    )                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                               
    cmd := &cobra.Command{                                                                                                                                                                                                                     
        Use:   "api <method> <path>",
        Short: "通用API调用",                                                                                                                                                                                                                  
        Args:  cobra.ExactArgs(2),                                                                                                                                                                                                             
        RunE: func(cmd *cobra.Command, args []string) error {                                                                                                                                                                                  
            method := args[0]                                                                                                                                                                                                                  
            path := args[1]                                                                                                                                                                                                                    
                                                                                                                                                                                                                                               
            // 加载配置                                                                                                                                                                                                                        
            cfg, err := core.LoadConfig()                                                                                                                                                                                                      
            if err != nil {                                                                                                                                                                                                                    
                return err                                                                                                                                                                                                                     
            }                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                               
            // 解析参数                                                                                                                                                                                                                        
            var queryMap map[string]interface{}
            if params != "" {                                                                                                                                                                                                                  
                if err := json.Unmarshal([]byte(params), &queryMap); err != nil {                                                                                                                                                              
                    return fmt.Errorf("--params 格式错误: %v", err)                                                                                                                                                                            
                }                                                                                                                                                                                                                              
            }                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                               
            var bodyData interface{}                                                                                                                                                                                                           
            if data != "" {                                                                                                                                                                                                                    
                if err := json.Unmarshal([]byte(data), &bodyData); err != nil {                                                                                                                                                                
                    return fmt.Errorf("--data 格式错误: %v", err)                                                                                                                                                                              
                }                                                                                                                                                                                                                              
            }                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                               
            // 构建请求                                                                                                                                                                                                                        
            req := &core.APIRequest{                                                                                                                                                                                                           
                Method: method,                                                                                                                                                                                                                
                Path:   path,                                                                                                                                                                                                                  
                Query:  queryMap,                                                                                                                                                                                                              
                Body:   bodyData,                                                                                                                                                                                                              
                As:     core.Identity(asType),                                                                                                                                                                                                 
            }                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                               
            // 执行请求                                                                                                                                                                                                                        
            c := client.NewClient(cfg)
            result, err := c.DoRequest(context.Background(), req)                                                                                                                                                                              
            if err != nil {                                                                                                                                                                                                                    
                return err                                                                                                                                                                                                                     
            }                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                               
            // 格式化输出                                                                                                                                                                                                                      
            output, _ := json.MarshalIndent(result, "", "  ")
            fmt.Println(string(output))                                                                                                                                                                                                        
                                                                                                                                                                                                                                               
            return nil                                                                                                                                                                                                                         
        },                                                                                                                                                                                                                                     
    }                                                                                                                                                                                                                                          
                
    cmd.Flags().StringVar(&params, "params", "", "查询参数 (JSON)")                                                                                                                                                                            
    cmd.Flags().StringVar(&data, "data", "", "请求体 (JSON)")
    cmd.Flags().StringVar(&asType, "as", "user", "身份类型: user | bot")                                                                                                                                                                       
                                                                                                                                                                                                                                               
    return cmd                                                                                                                                                                                                                                 
}                                                                                                                                                                                                                                              
                     