const os = require('os');                                                                                                                                                                                                                      
const path = require('path');                                                                                                                                                                                                                  
const fs = require('fs');                                                                                                                                                                                                                      
const https = require('https');                                                                                                                                                                                                                
                                                                                                                                                                                                                                             
const platform = os.platform();                                                                                                                                                                                                                
const arch = os.arch();                                                                                                                                                                                                                        
const version = require('../package.json').version;                                                                                                                                                                                            
                                                                                                                                                                                                                                             
const binaryName = platform === 'win32' ? 'soke-cli.exe' : 'soke-cli';                                                                                                                                                                     
const downloadURL = `https://github.com/你的组织/shouke-cli/releases/download/v${version}/shouke-cli-${platform}-${arch}`;    